<template>
  <div id="app">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <transition 
        name="router-anim"
    >
        <router-view 
            class="view"
            v-bind:dataset='dataset'
            v-bind:userInfo='userInfo'
            v-on:userInput='userInput'          
        >
        </router-view>
     </transition>
        <!-- <i class="arrow fas fa-caret-down"></i> -->
  </div>
</template>

<script>

export default {
  name: 'app',
  data(){
	  return{
        userInfo:{},
        dataset:[
            {
                jaartal: 2013,
                totaal: '???',
                pepperspray:[
                    {
                        maand:1,
                        aantal:'?'
                    },
                    {
                        maand:2,
                        aantal:'?'
                    },
                    {
                        maand:3,
                        aantal:'?'
                    },
                    {
                        maand:4,
                        aantal:'?'
                    },
                    {
                        maand:5,
                        aantal:'?'
                    },
                    {
                        maand:6,
                        aantal:'?'
                    },
                    {
                        maand:7,
                        aantal:'?'
                    },
                    {
                        maand:8,
                        aantal:'?'
                    },
                    {
                        maand:9,
                        aantal:'?'
                    },
                    {
                        maand:10,
                        aantal:'?'
                    },
                    {
                        maand:11,
                        aantal:'?'
                    },
                    {
                        maand:12,
                        aantal:'?'
                    },
                ],
                richten:[
                    {
                        maand:1,
                        aantal:'?'
                    },
                    {
                        maand:2,
                        aantal:'?'
                    },
                    {
                        maand:3,
                        aantal:'?'
                    },
                    {
                        maand:4,
                        aantal:'?'
                    },
                    {
                        maand:5,
                        aantal:'?'
                    },
                    {
                        maand:6,
                        aantal:'?'
                    },
                    {
                        maand:7,
                        aantal:'?'
                    },
                    {
                        maand:8,
                        aantal:'?'
                    },
                    {
                        maand:9,
                        aantal:'?'
                    },
                    {
                        maand:10,
                        aantal:'?'
                    },
                    {
                        maand:11,
                        aantal:'?'
                    },
                    {
                        maand:12,
                        aantal:'?'
                    },
                ],
                hond:[
                    {
                        maand:1,
                        aantal:'?'
                    },
                    {
                        maand:2,
                        aantal:'?'
                    },
                    {
                        maand:3,
                        aantal:'?'
                    },
                    {
                        maand:4,
                        aantal:'?'
                    },
                    {
                        maand:5,
                        aantal:'?'
                    },
                    {
                        maand:6,
                        aantal:'?'
                    },
                    {
                        maand:7,
                        aantal:'?'
                    },
                    {
                        maand:8,
                        aantal:'?'
                    },
                    {
                        maand:9,
                        aantal:'?'
                    },
                    {
                        maand:10,
                        aantal:'?'
                    },
                    {
                        maand:11,
                        aantal:'?'
                    },
                    {
                        maand:12,
                        aantal:'?'
                    },
                ],
                korteWapenstok:[
                    {
                        maand:1,
                        aantal:'?'
                    },
                    {
                        maand:2,
                        aantal:'?'
                    },
                    {
                        maand:3,
                        aantal:'?'
                    },
                    {
                        maand:4,
                        aantal:'?'
                    },
                    {
                        maand:5,
                        aantal:'?'
                    },
                    {
                        maand:6,
                        aantal:'?'
                    },
                    {
                        maand:7,
                        aantal:'?'
                    },
                    {
                        maand:8,
                        aantal:'?'
                    },
                    {
                        maand:9,
                        aantal:'?'
                    },
                    {
                        maand:10,
                        aantal:'?'
                    },
                    {
                        maand:11,
                        aantal:'?'
                    },
                    {
                        maand:12,
                        aantal:'?'
                    },
                ],
                langeWapenstok:[
                    {
                        maand:1,
                        aantal:'?'
                    },
                    {
                        maand:2,
                        aantal:'?'
                    },
                    {
                        maand:3,
                        aantal:'?'
                    },
                    {
                        maand:4,
                        aantal:'?'
                    },
                    {
                        maand:5,
                        aantal:'?'
                    },
                    {
                        maand:6,
                        aantal:'?'
                    },
                    {
                        maand:7,
                        aantal:'?'
                    },
                    {
                        maand:8,
                        aantal:'?'
                    },
                    {
                        maand:9,
                        aantal:'?'
                    },
                    {
                        maand:10,
                        aantal:'?'
                    },
                    {
                        maand:11,
                        aantal:'?'
                    },
                    {
                        maand:12,
                        aantal:'?'
                    },
                ],
                terHandNemen:[
                    {
                        maand:1,
                        aantal:'?'
                    },
                    {
                        maand:2,
                        aantal:'?'
                    },
                    {
                        maand:3,
                        aantal:'?'
                    },
                    {
                        maand:4,
                        aantal:'?'
                    },
                    {
                        maand:5,
                        aantal:'?'
                    },
                    {
                        maand:6,
                        aantal:'?'
                    },
                    {
                        maand:7,
                        aantal:'?'
                    },
                    {
                        maand:8,
                        aantal:'?'
                    },
                    {
                        maand:9,
                        aantal:'?'
                    },
                    {
                        maand:10,
                        aantal:'?'
                    },
                    {
                        maand:11,
                        aantal:'?'
                    },
                    {
                        maand:12,
                        aantal:'?'
                    },
                ],
                waarschuwingsSchot:[
                    {
                        maand:1,
                        aantal:'?'
                    },
                    {
                        maand:2,
                        aantal:'?'
                    },
                    {
                        maand:3,
                        aantal:'?'
                    },
                    {
                        maand:4,
                        aantal:'?'
                    },
                    {
                        maand:5,
                        aantal:'?'
                    },
                    {
                        maand:6,
                        aantal:'?'
                    },
                    {
                        maand:7,
                        aantal:'?'
                    },
                    {
                        maand:8,
                        aantal:'?'
                    },
                    {
                        maand:9,
                        aantal:'?'
                    },
                    {
                        maand:10,
                        aantal:'?'
                    },
                    {
                        maand:11,
                        aantal:'?'
                    },
                    {
                        maand:12,
                        aantal:'?'
                    },
                ]
                
            },
            {
                jaartal: 2014,
                totaal: 2588,
                pepperspray:[
                    {
                        maand:1,
                        aantal:89
                    },
                    {
                        maand:2,
                        aantal:72
                    },
                    {
                        maand:3,
                        aantal:89
                    },
                    {
                        maand:4,
                        aantal:87
                    },
                    {
                        maand:5,
                        aantal:74
                    },
                    {
                        maand:6,
                        aantal:75
                    },
                    {
                        maand:7,
                        aantal:85
                    },
                    {
                        maand:8,
                        aantal:92
                    },
                    {
                        maand:9,
                        aantal:69
                    },
                    {
                        maand:10,
                        aantal:65
                    },
                    {
                        maand:11,
                        aantal:59
                    },
                    {
                        maand:12,
                        aantal:62
                    },
                ],
                richten:[
                    {
                        maand:1,
                        aantal:64
                    },
                    {
                        maand:2,
                        aantal:64
                    },
                    {
                        maand:3,
                        aantal:72
                    },
                    {
                        maand:4,
                        aantal:81
                    },
                    {
                        maand:5,
                        aantal:75
                    },
                    {
                        maand:6,
                        aantal:62
                    },
                    {
                        maand:7,
                        aantal:48
                    },
                    {
                        maand:8,
                        aantal:35
                    },
                    {
                        maand:9,
                        aantal:48
                    },
                    {
                        maand:10,
                        aantal:61
                    },
                    {
                        maand:11,
                        aantal:78
                    },
                    {
                        maand:12,
                        aantal:53
                    },
                ],
                hond:[
                    {
                        maand:1,
                        aantal:23
                    },
                    {
                        maand:2,
                        aantal:12
                    },
                    {
                        maand:3,
                        aantal:27
                    },
                    {
                        maand:4,
                        aantal:22
                    },
                    {
                        maand:5,
                        aantal:27
                    },
                    {
                        maand:6,
                        aantal:29
                    },
                    {
                        maand:7,
                        aantal:17
                    },
                    {
                        maand:8,
                        aantal:24
                    },
                    {
                        maand:9,
                        aantal:19
                    },
                    {
                        maand:10,
                        aantal:19
                    },
                    {
                        maand:11,
                        aantal:27
                    },
                    {
                        maand:12,
                        aantal:13
                    },
                ],
                korteWapenstok:[
                    {
                        maand:1,
                        aantal:9
                    },
                    {
                        maand:2,
                        aantal:9
                    },
                    {
                        maand:3,
                        aantal:15
                    },
                    {
                        maand:4,
                        aantal:17
                    },
                    {
                        maand:5,
                        aantal:10
                    },
                    {
                        maand:6,
                        aantal:25
                    },
                    {
                        maand:7,
                        aantal:10
                    },
                    {
                        maand:8,
                        aantal:16
                    },
                    {
                        maand:9,
                        aantal:27
                    },
                    {
                        maand:10,
                        aantal:19
                    },
                    {
                        maand:11,
                        aantal:14
                    },
                    {
                        maand:12,
                        aantal:8
                    },
                ],
                langeWapenstok:[
                    {
                        maand:1,
                        aantal:16
                    },
                    {
                        maand:2,
                        aantal:9
                    },
                    {
                        maand:3,
                        aantal:9
                    },
                    {
                        maand:4,
                        aantal:12
                    },
                    {
                        maand:5,
                        aantal:8
                    },
                    {
                        maand:6,
                        aantal:8
                    },
                    {
                        maand:7,
                        aantal:6
                    },
                    {
                        maand:8,
                        aantal:21
                    },
                    {
                        maand:9,
                        aantal:8
                    },
                    {
                        maand:10,
                        aantal:17
                    },
                    {
                        maand:11,
                        aantal:14
                    },
                    {
                        maand:12,
                        aantal:14
                    },
                ],
                terHandNemen:[
                    {
                        maand:1,
                        aantal:19
                    },
                    {
                        maand:2,
                        aantal:27
                    },
                    {
                        maand:3,
                        aantal:30
                    },
                    {
                        maand:4,
                        aantal:23
                    },
                    {
                        maand:5,
                        aantal:23
                    },
                    {
                        maand:6,
                        aantal:20
                    },
                    {
                        maand:7,
                        aantal:36
                    },
                    {
                        maand:8,
                        aantal:26
                    },
                    {
                        maand:9,
                        aantal:23
                    },
                    {
                        maand:10,
                        aantal:26
                    },
                    {
                        maand:11,
                        aantal:20
                    },
                    {
                        maand:12,
                        aantal:15
                    },
                ],
                waarschuwingsSchot:[
                    {
                        maand:1,
                        aantal:5
                    },
                    {
                        maand:2,
                        aantal:1
                    },
                    {
                        maand:3,
                        aantal:5
                    },
                    {
                        maand:4,
                        aantal:11
                    },
                    {
                        maand:5,
                        aantal:5
                    },
                    {
                        maand:6,
                        aantal:2
                    },
                    {
                        maand:7,
                        aantal:6
                    },
                    {
                        maand:8,
                        aantal:10
                    },
                    {
                        maand:9,
                        aantal:4
                    },
                    {
                        maand:10,
                        aantal:6
                    },
                    {
                        maand:11,
                        aantal:5
                    },
                    {
                        maand:12,
                        aantal:1
                    },
                ]
                
            },
            {
                jaartal: 2015,
                totaal: 2696,
                pepperspray:[
                    {
                        maand:1,
                        aantal:69
                    },
                    {
                        maand:2,
                        aantal:82
                    },
                    {
                        maand:3,
                        aantal:74
                    },
                    {
                        maand:4,
                        aantal:72
                    },
                    {
                        maand:5,
                        aantal:98
                    },
                    {
                        maand:6,
                        aantal:66
                    },
                    {
                        maand:7,
                        aantal:90
                    },
                    {
                        maand:8,
                        aantal:113
                    },
                    {
                        maand:9,
                        aantal:81
                    },
                    {
                        maand:10,
                        aantal:79
                    },
                    {
                        maand:11,
                        aantal:63
                    },
                    {
                        maand:12,
                        aantal:94
                    },
                ],
                richten:[
                    {
                        maand:1,
                        aantal:59
                    },
                    {
                        maand:2,
                        aantal:105
                    },
                    {
                        maand:3,
                        aantal:62
                    },
                    {
                        maand:4,
                        aantal:85
                    },
                    {
                        maand:5,
                        aantal:72
                    },
                    {
                        maand:6,
                        aantal:57
                    },
                    {
                        maand:7,
                        aantal:86
                    },
                    {
                        maand:8,
                        aantal:68
                    },
                    {
                        maand:9,
                        aantal:55
                    },
                    {
                        maand:10,
                        aantal:74
                    },
                    {
                        maand:11,
                        aantal:68
                    },
                    {
                        maand:12,
                        aantal:75
                    },
                ],
                hond:[
                    {
                        maand:1,
                        aantal:19
                    },
                    {
                        maand:2,
                        aantal:17
                    },
                    {
                        maand:3,
                        aantal:11
                    },
                    {
                        maand:4,
                        aantal:23
                    },
                    {
                        maand:5,
                        aantal:22
                    },
                    {
                        maand:6,
                        aantal:20
                    },
                    {
                        maand:7,
                        aantal:18
                    },
                    {
                        maand:8,
                        aantal:32
                    },
                    {
                        maand:9,
                        aantal:18
                    },
                    {
                        maand:10,
                        aantal:16
                    },
                    {
                        maand:11,
                        aantal:18
                    },
                    {
                        maand:12,
                        aantal:11
                    },
                ],
                korteWapenstok:[
                    {
                        maand:1,
                        aantal:13
                    },
                    {
                        maand:2,
                        aantal:16
                    },
                    {
                        maand:3,
                        aantal:12
                    },
                    {
                        maand:4,
                        aantal:4
                    },
                    {
                        maand:5,
                        aantal:13
                    },
                    {
                        maand:6,
                        aantal:13
                    },
                    {
                        maand:7,
                        aantal:12
                    },
                    {
                        maand:8,
                        aantal:48
                    },
                    {
                        maand:9,
                        aantal:28
                    },
                    {
                        maand:10,
                        aantal:13
                    },
                    {
                        maand:11,
                        aantal:7
                    },
                    {
                        maand:12,
                        aantal:17
                    },
                ],
                langeWapenstok:[
                    {
                        maand:1,
                        aantal:22
                    },
                    {
                        maand:2,
                        aantal:7
                    },
                    {
                        maand:3,
                        aantal:7
                    },
                    {
                        maand:4,
                        aantal:12
                    },
                    {
                        maand:5,
                        aantal:8
                    },
                    {
                        maand:6,
                        aantal:17
                    },
                    {
                        maand:7,
                        aantal:13
                    },
                    {
                        maand:8,
                        aantal:18
                    },
                    {
                        maand:9,
                        aantal:11
                    },
                    {
                        maand:10,
                        aantal:2
                    },
                    {
                        maand:11,
                        aantal:6
                    },
                    {
                        maand:12,
                        aantal:11
                    },
                ],
                terHandNemen:[
                    {
                        maand:1,
                        aantal:21
                    },
                    {
                        maand:2,
                        aantal:32
                    },
                    {
                        maand:3,
                        aantal:26
                    },
                    {
                        maand:4,
                        aantal:10
                    },
                    {
                        maand:5,
                        aantal:13
                    },
                    {
                        maand:6,
                        aantal:13
                    },
                    {
                        maand:7,
                        aantal:15
                    },
                    {
                        maand:8,
                        aantal:25
                    },
                    {
                        maand:9,
                        aantal:23
                    },
                    {
                        maand:10,
                        aantal:17
                    },
                    {
                        maand:11,
                        aantal:15
                    },
                    {
                        maand:12,
                        aantal:27
                    },
                ],
                waarschuwingsSchot:[
                    {
                        maand:1,
                        aantal:5
                    },
                    {
                        maand:2,
                        aantal:6
                    },
                    {
                        maand:3,
                        aantal:6
                    },
                    {
                        maand:4,
                        aantal:5
                    },
                    {
                        maand:5,
                        aantal:3
                    },
                    {
                        maand:6,
                        aantal:7
                    },
                    {
                        maand:7,
                        aantal:4
                    },
                    {
                        maand:8,
                        aantal:6
                    },
                    {
                        maand:9,
                        aantal:4
                    },
                    {
                        maand:10,
                        aantal:1
                    },
                    {
                        maand:11,
                        aantal:5
                    },
                    {
                        maand:12,
                        aantal:5
                    },
                ]
                
            },
            {
                jaartal: 2016,
                totaal: 2643,
                pepperspray:[
                    {
                        maand:1,
                        aantal:80
                    },
                    {
                        maand:2,
                        aantal:80
                    },
                    {
                        maand:3,
                        aantal:58
                    },
                    {
                        maand:4,
                        aantal:73
                    },
                    {
                        maand:5,
                        aantal:80
                    },
                    {
                        maand:6,
                        aantal:82
                    },
                    {
                        maand:7,
                        aantal:87
                    },
                    {
                        maand:8,
                        aantal:87
                    },
                    {
                        maand:9,
                        aantal:105
                    },
                    {
                        maand:10,
                        aantal:70
                    },
                    {
                        maand:11,
                        aantal:57
                    },
                    {
                        maand:12,
                        aantal:59
                    },
                ],
                richten:[
                    {
                        maand:1,
                        aantal:70
                    },
                    {
                        maand:2,
                        aantal:86
                    },
                    {
                        maand:3,
                        aantal:94
                    },
                    {
                        maand:4,
                        aantal:91
                    },
                    {
                        maand:5,
                        aantal:106
                    },
                    {
                        maand:6,
                        aantal:112
                    },
                    {
                        maand:7,
                        aantal:90
                    },
                    {
                        maand:8,
                        aantal:110
                    },
                    {
                        maand:9,
                        aantal:95
                    },
                    {
                        maand:10,
                        aantal:69
                    },
                    {
                        maand:11,
                        aantal:57
                    },
                    {
                        maand:12,
                        aantal:66
                    },
                ],
                hond:[
                    {
                        maand:1,
                        aantal:14
                    },
                    {
                        maand:2,
                        aantal:17
                    },
                    {
                        maand:3,
                        aantal:9
                    },
                    {
                        maand:4,
                        aantal:24
                    },
                    {
                        maand:5,
                        aantal:23
                    },
                    {
                        maand:6,
                        aantal:19
                    },
                    {
                        maand:7,
                        aantal:15
                    },
                    {
                        maand:8,
                        aantal:14
                    },
                    {
                        maand:9,
                        aantal:21
                    },
                    {
                        maand:10,
                        aantal:15
                    },
                    {
                        maand:11,
                        aantal:6
                    },
                    {
                        maand:12,
                        aantal:11
                    },
                ],
                korteWapenstok:[
                    {
                        maand:1,
                        aantal:17
                    },
                    {
                        maand:2,
                        aantal:18
                    },
                    {
                        maand:3,
                        aantal:5
                    },
                    {
                        maand:4,
                        aantal:10
                    },
                    {
                        maand:5,
                        aantal:19
                    },
                    {
                        maand:6,
                        aantal:13
                    },
                    {
                        maand:7,
                        aantal:10
                    },
                    {
                        maand:8,
                        aantal:14
                    },
                    {
                        maand:9,
                        aantal:7
                    },
                    {
                        maand:10,
                        aantal:5
                    },
                    {
                        maand:11,
                        aantal:6
                    },
                    {
                        maand:12,
                        aantal:8
                    },
                ],
                langeWapenstok:[
                    {
                        maand:1,
                        aantal:42
                    },
                    {
                        maand:2,
                        aantal:9
                    },
                    {
                        maand:3,
                        aantal:6
                    },
                    {
                        maand:4,
                        aantal:15
                    },
                    {
                        maand:5,
                        aantal:8
                    },
                    {
                        maand:6,
                        aantal:13
                    },
                    {
                        maand:7,
                        aantal:7
                    },
                    {
                        maand:8,
                        aantal:6
                    },
                    {
                        maand:9,
                        aantal:8
                    },
                    {
                        maand:10,
                        aantal:14
                    },
                    {
                        maand:11,
                        aantal:6
                    },
                    {
                        maand:12,
                        aantal:11
                    },
                ],
                terHandNemen:[
                    {
                        maand:1,
                        aantal:16
                    },
                    {
                        maand:2,
                        aantal:7
                    },
                    {
                        maand:3,
                        aantal:15
                    },
                    {
                        maand:4,
                        aantal:15
                    },
                    {
                        maand:5,
                        aantal:19
                    },
                    {
                        maand:6,
                        aantal:9
                    },
                    {
                        maand:7,
                        aantal:25
                    },
                    {
                        maand:8,
                        aantal:9
                    },
                    {
                        maand:9,
                        aantal:10
                    },
                    {
                        maand:10,
                        aantal:8
                    },
                    {
                        maand:11,
                        aantal:8
                    },
                    {
                        maand:12,
                        aantal:14
                    },
                ],
                waarschuwingsSchot:[
                    {
                        maand:1,
                        aantal:3
                    },
                    {
                        maand:2,
                        aantal:7
                    },
                    {
                        maand:3,
                        aantal:10
                    },
                    {
                        maand:4,
                        aantal:5
                    },
                    {
                        maand:5,
                        aantal:7
                    },
                    {
                        maand:6,
                        aantal:6
                    },
                    {
                        maand:7,
                        aantal:3
                    },
                    {
                        maand:8,
                        aantal:3
                    },
                    {
                        maand:9,
                        aantal:2
                    },
                    {
                        maand:10,
                        aantal:1
                    },
                    {
                        maand:11,
                        aantal:5
                    },
                    {
                        maand:12,
                        aantal:7
                    },
                ]
                
            },
            {
                jaartal: 2017,
                totaal: 2318,
                pepperspray:[
                    {
                        maand:1,
                        aantal:55
                    },
                    {
                        maand:2,
                        aantal:57
                    },
                    {
                        maand:3,
                        aantal:60
                    },
                    {
                        maand:4,
                        aantal:60
                    },
                    {
                        maand:5,
                        aantal:86
                    },
                    {
                        maand:6,
                        aantal:66
                    },
                    {
                        maand:7,
                        aantal:72
                    },
                    {
                        maand:8,
                        aantal:86
                    },
                    {
                        maand:9,
                        aantal:53
                    },
                    {
                        maand:10,
                        aantal:62
                    },
                    {
                        maand:11,
                        aantal:64
                    },
                    {
                        maand:12,
                        aantal:55
                    },
                ],
                richten:[
                    {
                        maand:1,
                        aantal:71
                    },
                    {
                        maand:2,
                        aantal:51
                    },
                    {
                        maand:3,
                        aantal:68
                    },
                    {
                        maand:4,
                        aantal:52
                    },
                    {
                        maand:5,
                        aantal:70
                    },
                    {
                        maand:6,
                        aantal:73
                    },
                    {
                        maand:7,
                        aantal:59
                    },
                    {
                        maand:8,
                        aantal:51
                    },
                    {
                        maand:9,
                        aantal:48
                    },
                    {
                        maand:10,
                        aantal:68
                    },
                    {
                        maand:11,
                        aantal:65
                    },
                    {
                        maand:12,
                        aantal:81
                    },
                ],
                hond:[
                    {
                        maand:1,
                        aantal:16
                    },
                    {
                        maand:2,
                        aantal:10
                    },
                    {
                        maand:3,
                        aantal:7
                    },
                    {
                        maand:4,
                        aantal:13
                    },
                    {
                        maand:5,
                        aantal:18
                    },
                    {
                        maand:6,
                        aantal:9
                    },
                    {
                        maand:7,
                        aantal:23
                    },
                    {
                        maand:8,
                        aantal:19
                    },
                    {
                        maand:9,
                        aantal:16
                    },
                    {
                        maand:10,
                        aantal:16
                    },
                    {
                        maand:11,
                        aantal:19
                    },
                    {
                        maand:12,
                        aantal:10
                    },
                ],
                korteWapenstok:[
                    {
                        maand:1,
                        aantal:15
                    },
                    {
                        maand:2,
                        aantal:8
                    },
                    {
                        maand:3,
                        aantal:7
                    },
                    {
                        maand:4,
                        aantal:6
                    },
                    {
                        maand:5,
                        aantal:7
                    },
                    {
                        maand:6,
                        aantal:11
                    },
                    {
                        maand:7,
                        aantal:15
                    },
                    {
                        maand:8,
                        aantal:13
                    },
                    {
                        maand:9,
                        aantal:4
                    },
                    {
                        maand:10,
                        aantal:7
                    },
                    {
                        maand:11,
                        aantal:11
                    },
                    {
                        maand:12,
                        aantal:18
                    },
                ],
                langeWapenstok:[
                    {
                        maand:1,
                        aantal:8
                    },
                    {
                        maand:2,
                        aantal:5
                    },
                    {
                        maand:3,
                        aantal:13
                    },
                    {
                        maand:4,
                        aantal:6
                    },
                    {
                        maand:5,
                        aantal:26
                    },
                    {
                        maand:6,
                        aantal:8
                    },
                    {
                        maand:7,
                        aantal:17
                    },
                    {
                        maand:8,
                        aantal:7
                    },
                    {
                        maand:9,
                        aantal:10
                    },
                    {
                        maand:10,
                        aantal:5
                    },
                    {
                        maand:11,
                        aantal:5
                    },
                    {
                        maand:12,
                        aantal:21
                    },
                ],
                terHandNemen:[
                    {
                        maand:1,
                        aantal:10
                    },
                    {
                        maand:2,
                        aantal:8
                    },
                    {
                        maand:3,
                        aantal:8
                    },
                    {
                        maand:4,
                        aantal:13
                    },
                    {
                        maand:5,
                        aantal:20
                    },
                    {
                        maand:6,
                        aantal:11
                    },
                    {
                        maand:7,
                        aantal:12
                    },
                    {
                        maand:8,
                        aantal:19
                    },
                    {
                        maand:9,
                        aantal:7
                    },
                    {
                        maand:10,
                        aantal:15
                    },
                    {
                        maand:11,
                        aantal:25
                    },
                    {
                        maand:12,
                        aantal:23
                    },
                ],
                waarschuwingsSchot:[
                    {
                        maand:1,
                        aantal:4
                    },
                    {
                        maand:2,
                        aantal:1
                    },
                    {
                        maand:3,
                        aantal:11
                    },
                    {
                        maand:4,
                        aantal:6
                    },
                    {
                        maand:5,
                        aantal:0
                    },
                    {
                        maand:6,
                        aantal:7
                    },
                    {
                        maand:7,
                        aantal:4
                    },
                    {
                        maand:8,
                        aantal:7
                    },
                    {
                        maand:9,
                        aantal:4
                    },
                    {
                        maand:10,
                        aantal:2
                    },
                    {
                        maand:11,
                        aantal:12
                    },
                    {
                        maand:12,
                        aantal:2
                    },
                ]
                
            },
            {
                jaartal: 2018,
                totaal: 1094,
                pepperspray:[
                    {
                        maand:1,
                        aantal:33
                    },
                    {
                        maand:2,
                        aantal:40
                    },
                    {
                        maand:3,
                        aantal:46
                    },
                    {
                        maand:4,
                        aantal:70
                    },
                    {
                        maand:5,
                        aantal:80
                    },
                    {
                        maand:6,
                        aantal:65
                    },
                    {
                        maand:7,
                        aantal:'?'
                    },
                    {
                        maand:8,
                        aantal:'?'
                    },
                    {
                        maand:9,
                        aantal:'?'
                    },
                    {
                        maand:10,
                        aantal:'?'
                    },
                    {
                        maand:11,
                        aantal:'?'
                    },
                    {
                        maand:12,
                        aantal:'?'
                    },
                ],
                richten:[
                    {
                        maand:1,
                        aantal:49
                    },
                    {
                        maand:2,
                        aantal:61
                    },
                    {
                        maand:3,
                        aantal:72
                    },
                    {
                        maand:4,
                        aantal:90
                    },
                    {
                        maand:5,
                        aantal:74
                    },
                    {
                        maand:6,
                        aantal:81
                    },
                    {
                        maand:7,
                        aantal:'?'
                    },
                    {
                        maand:8,
                        aantal:'?'
                    },
                    {
                        maand:9,
                        aantal:'?'
                    },
                    {
                        maand:10,
                        aantal:'?'
                    },
                    {
                        maand:11,
                        aantal:'?'
                    },
                    {
                        maand:12,
                        aantal:'?'
                    },
                ],
                hond:[
                    {
                        maand:1,
                        aantal:15
                    },
                    {
                        maand:2,
                        aantal:13
                    },
                    {
                        maand:3,
                        aantal:11
                    },
                    {
                        maand:4,
                        aantal:7
                    },
                    {
                        maand:5,
                        aantal:11
                    },
                    {
                        maand:6,
                        aantal:19
                    },
                    {
                        maand:7,
                        aantal:'?'
                    },
                    {
                        maand:8,
                        aantal:'?'
                    },
                    {
                        maand:9,
                        aantal:'?'
                    },
                    {
                        maand:10,
                        aantal:'?'
                    },
                    {
                        maand:11,
                        aantal:'?'
                    },
                    {
                        maand:12,
                        aantal:'?'
                    },
                ],
                korteWapenstok:[
                    {
                        maand:1,
                        aantal:12
                    },
                    {
                        maand:2,
                        aantal:14
                    },
                    {
                        maand:3,
                        aantal:11
                    },
                    {
                        maand:4,
                        aantal:9
                    },
                    {
                        maand:5,
                        aantal:12
                    },
                    {
                        maand:6,
                        aantal:9
                    },
                    {
                        maand:7,
                        aantal:'?'
                    },
                    {
                        maand:8,
                        aantal:'?'
                    },
                    {
                        maand:9,
                        aantal:'?'
                    },
                    {
                        maand:10,
                        aantal:'?'
                    },
                    {
                        maand:11,
                        aantal:'?'
                    },
                    {
                        maand:12,
                        aantal:'?'
                    },
                ],
                langeWapenstok:[
                    {
                        maand:1,
                        aantal:20
                    },
                    {
                        maand:2,
                        aantal:2
                    },
                    {
                        maand:3,
                        aantal:4
                    },
                    {
                        maand:4,
                        aantal:10
                    },
                    {
                        maand:5,
                        aantal:7
                    },
                    {
                        maand:6,
                        aantal:8
                    },
                    {
                        maand:7,
                        aantal:'?'
                    },
                    {
                        maand:8,
                        aantal:'?'
                    },
                    {
                        maand:9,
                        aantal:'?'
                    },
                    {
                        maand:10,
                        aantal:'?'
                    },
                    {
                        maand:11,
                        aantal:'?'
                    },
                    {
                        maand:12,
                        aantal:'?'
                    },
                ],
                terHandNemen:[
                    {
                        maand:1,
                        aantal:20
                    },
                    {
                        maand:2,
                        aantal:9
                    },
                    {
                        maand:3,
                        aantal:17
                    },
                    {
                        maand:4,
                        aantal:36
                    },
                    {
                        maand:5,
                        aantal:25
                    },
                    {
                        maand:6,
                        aantal:10
                    },
                    {
                        maand:7,
                        aantal:'?'
                    },
                    {
                        maand:8,
                        aantal:'?'
                    },
                    {
                        maand:9,
                        aantal:'?'
                    },
                    {
                        maand:10,
                        aantal:'?'
                    },
                    {
                        maand:11,
                        aantal:'?'
                    },
                    {
                        maand:12,
                        aantal:'?'
                    },
                ],
                waarschuwingsSchot:[
                    {
                        maand:1,
                        aantal:5
                    },
                    {
                        maand:2,
                        aantal:5
                    },
                    {
                        maand:3,
                        aantal:4
                    },
                    {
                        maand:4,
                        aantal:3
                    },
                    {
                        maand:5,
                        aantal:3
                    },
                    {
                        maand:6,
                        aantal:2
                    },
                    {
                        maand:7,
                        aantal:'?'
                    },
                    {
                        maand:8,
                        aantal:'?'
                    },
                    {
                        maand:9,
                        aantal:'?'
                    },
                    {
                        maand:10,
                        aantal:'?'
                    },
                    {
                        maand:11,
                        aantal:'?'
                    },
                    {
                        maand:12,
                        aantal:'?'
                    },
                ]
                
            },
        ]

	  }
  },
  components: {
  },
  methods:{
      userInput(prop, value){
          this.userInfo[prop] = value
          console.log(this.userInfo)
      }
  },
}
</script>

<style>
/* Global elements styling 
################################*/
body{
    overflow: hidden;
    background: black;
    height: 100vh;
    margin: 0;
}
.view{
    width: 100vw;
    height: 100vh;
    background: black;
    color: white;
    position: fixed;
}
#app {
  font-family: 'Roboto Condensed', sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
      display: flex;
    justify-content: center;
}

h1{
    margin: 10px;
    font-size: 40px;
}
h2{
    margin: 0;
}
p{
    margin: 10px auto;
    width: 80%;
    max-width: 600px;
}
p,li,h2,h1,span{
     -webkit-touch-callout: none; /* iOS Safari */
    -webkit-user-select: none; /* Safari */
     -khtml-user-select: none; /* Konqueror HTML */
       -moz-user-select: none; /* Firefox */
        -ms-user-select: none; /* Internet Explorer/Edge */
            user-select: none; /* Non-prefixed version, currently
                                  supported by Chrome and Opera */
}
li{
	list-style: none;
    
}
span{
    font-family: 'Special Elite', cursive;
}
/* Verschillende viewheights voor de content */
.content-10vh{
    height: 15vh;
}
.content-15vh{
    height: 15vh;
}
.content-20vh{
    height: 20vh;
}
.content-25vh{
    height: 25vh;
}
.content-30vh{
    margin-top: 30vh;
    height: 30vh;
}
.content-40vh{
    height: 40vh;
}
.content-50vh{
    height: 50vh;
}
.content{
    height: 50vh;
    display: flex;
    justify-content: space-around;
    flex-direction: column;
}
.red{
    color: #A03029;
}
.white{
    color: white;
}
.onbekend{
    font-size: 15px;
    margin: auto !important;
    color: #A03029;

}

/* Globale input styling 
################################*/
label{
	color: #bf975a;
	font-size: 25px;
}
select{
    margin-top: 10px;
	padding: 3px;
	width: 200px;
	outline: none;
    text-align: center;
}
svg > path{
  transition: .25s;
}



/* Position styling classes 
################################*/
.flexCenter{
	display: flex;
	justify-content: center;
	align-items: center;
	flex-direction: column;
}
.flexAround{
	display: flex;
	justify-content: space-around;
	align-items: center;
	flex-direction: column;
}
.flexBetween{
	display: flex;
	justify-content: space-between;
	align-items: center;
	flex-direction: column;
}



/* Styling States 
################################*/
.invisible{
  opacity: 0;
}



/* Default button styling de rest staan in de buttons component
################################*/
button{
    background: transparent;
    border: black solid 1px;
    outline: none;
    padding: 10px 20px;
    width: 150px;
    font-weight: 600;
    transition: .25s;
    cursor: pointer;
}
button:hover{
    background: white;
    color: black;
}
.buttons{
    display: flex;
    width: 80%;
    justify-content: space-around;
    align-items: center;
    margin: 10px;
    margin: auto; 
    max-width: 400px;
}




/* Pages styling
################################*/
.totaal{
    background: #A03029;
    width: 30%;
    /* height: 60%; */
    padding: 5px 15px;
}
.results-container{
    margin-top: 50px;
}
.results{
    display: flex;
    width: 80%;
    justify-content: space-around;
}
.results-ja > p, .results-nee > p {
    margin: 10px;
}
.result-anim-enter-active{
    animation: slideInResult 4s forwards;
}
@keyframes slideInResult {
    from{transform: translate(0,50px);opacity: 0;}
    to{transform: translate(0,0);opacity: 1;}
}
.percentage-1,.percentage-2{
    font-family: 'Special Elite', cursive;
    font-size: 36px;
    color: red;
}

/* Scrollbar 
################################*/

/* width */
::-webkit-scrollbar {
  width: 5px;
}

/* Track */
::-webkit-scrollbar-track {
  background: #f1f1f1; 
}
 
/* Handle */
::-webkit-scrollbar-thumb {
  background: #888; 
}

/* Handle on hover */
::-webkit-scrollbar-thumb:hover {
  background: #555; 
}

/* Globale keyframes 
################################*/

/* Dissapear elements through the top */
.router-anim-leave-active{
    animation: slideOutTop 2s forwards;
}
.router-anim-enter-active{
    animation: slideOutBottom 2s forwards;
}

.arrow{
    position: fixed;
    bottom: 2vh;
    font-size: 3em;
    animation: arrow-anim 2.5s;
    animation-iteration-count: infinite;
    animation-direction: alternate;
    transform-origin: center;
    z-index: 10;
    margin: auto;
    left: 0;
    right: 0;
}
@keyframes arrow-anim {
    from{transform: scale(1);}
    to{transform: scale(1.2)}
}

@keyframes slideOutTop{
  from {transform: translate(0, 0);}
  to {transform: translate(0, -100vh)}
}

@keyframes slideOutBottom{
  from {transform: translate(0, 100vh);}
  to {transform: translate(0, 0)}
}

@keyframes opacityAnim{
  from {opacity: 0;}
  to {opacity: 1;}
}

</style>
